name: Build and deploy Jekyll site to AWS S3
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Jekyll
        shell: bash -l {0}
        run: |
          gem install jekyll bundler
          bundle install
      - name: Build Jekyll
        shell: bash -l {0}
        run: |
          bundle exec jekyll build
          ls ./_site
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync _site/ s3://preview.quantecon.org/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"